name: Release version

on:
  push:
    branches: main

permissions:
  contents: write
  issues: read

jobs:
  release-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        runs: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
